
services:
  api:
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=112233
      - DB_NAME=data
      - CONFIG_PATH=/config.yaml
    volumes:
      - ./config.yaml:/config/config.yaml
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 112233
      POSTGRES_DB: data
    ports:
      - "1000:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
