version: '3.9'

services:
  db:
    image: postgres:17.2-alpine
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
    - pg_data:/var/lib/postgresql/data
    ports:
    - "1000:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang_api
    depends_on:
      - db
    volumes:
      - ./config.yaml:/app/config.yaml
    ports:
      - "4000:4000"
volumes:
  pg_data: